# Generated by Django 3.1.7 on 2021-02-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('expira', models.DateField()),
                ('alerta1y', models.BooleanField()),
                ('alerta6m', models.BooleanField()),
                ('alerta3m', models.BooleanField()),
                ('alerta1m', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
